# Generated by Django 5.2.8 on 2025-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate Event'), ('party', 'Party'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
