# Generated by Django 5.2.8 on 2026-03-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_venuebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='purpose',
        ),
    ]
